[package]
name = "day03"
version = "0.1.0"
authors = ["Dodo <kasper199914@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
regex = "*"
aoc = {version = "*", git = "https://github.com/DutchGhost/aoc"}