[package]
name = "day04_2"
version = "0.1.0"
authors = ["Dodo <kasper199914@gmail.com>"]
edition = "2018"

[dependencies]
aoc = {version = "*", git = "https://github.com/DutchGhost/aoc"}
chrono = "*"
